Fix Driver Sequelize : null check with reference id
the-labo/the pull request #51
Opened 2020-10-20 04:37 UTC by sansoohan

Cascade する時、すでに Null になった物を参照することがある。

2020-10-20 05:56 UTC, FujiHaruka commented
@sansoohan 

テストケースの追加がほしいです。不具合修正は基本的に、

1. 現状では失敗するテストケースを書く→不具合の再現性がこれで証明できる
2. 不具合修正のコード変更を行う

の手順でやってもらえるとレビューしやすいです

2020-10-20 06:33 UTC, sansoohan commented
@FujiHaruka 
db テストコード実行しました。
db の作成が必要だと思いますが。docker-file などのDB作成のことが見当たらないです。
db 作成などを含めて、the シリーズのデバッグのドキュメントはありますか？

2020-10-20 07:06 UTC, FujiHaruka commented
@sansoohan 

ドキュメントは特にないのでソースコードを読んでいきます。MySQL の Docker コンテナを起動するスクリプトは

- https://github.com/the-labo/the/blob/master/packages/db/misc/mysql/server.sh
- https://github.com/the-labo/the/blob/master/packages/driver-sequelize/misc/mysql/server.sh

があります。

2020-10-20 09:39 UTC, FujiHaruka commented
@sansoohan テストコードのコミットはこの PR に含めてほしいです。

2020-10-20 13:38 UTC, FujiHaruka commented
@sansoohan 

4d7bf50 で追加されたテストケースはコードの変更 e44506d がなくても通るテストですね。

> Cascade する時、すでに Null になった物を参照することがある。

これを再現するテストは書けますか？

2020-10-21 05:27 UTC, okunishinishi commented on packages/driver-sequelize/lib/TheDriverSequelize.js
> +        }
vがない時のreturnも欲しいですね。これだとvがfalseや0がきた時にundefinedになってしまいますね

2020-10-21 05:28 UTC, okunishinishi requested changes
https://github.com/the-labo/the/pull/51/files#r508998288

2020-10-21 05:31 UTC, okunishinishi commented on packages/driver-sequelize/lib/TheDriverSequelize.js
> +        }
```javascript
if(!v) {
   return v
}
return this.outbound(v.constructor.name, v.dataValues)
```

2020-10-21 06:18 UTC, sansoohan commented on packages/driver-sequelize/lib/TheDriverSequelize.js
> +        }
@okunishinishi 
修正しました。

2020-10-22 01:13 UTC, FujiHaruka commented
そもそもテストケースでエラーが再現しないなら、この修正に意味があるかどうかはわからないのではないですか？

2020-10-22 08:35 UTC, okunishinishi requested changes
> そもそもテストケースでエラーが再現しないなら、この修正に意味があるかどうかはわからないのではないですか？

同感

2020-10-22 10:24 UTC, okunishinishi commented
https://github.com/the-labo/the/pull/51 で対応されたのでこのPRはクローズ

2020-10-22 10:24 UTC, closed without merging